server:
  servlet:
    context-path: /aws

logging:
  level:
    academy.wakanda: ${LOG_LEVEL:DEBUG}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_SNS_ACCESS_KEY:teste}
      secretKey: ${AWS_SNS_SECRET_KEY:teste}
    stack: false
    stack.auto: false
    region:
      auto: false
      static: ${AWS_SNS_REGION:us-east-1}
      use-default-aws-region-chain: true

aws:
  config:
    region: ${AWS_SNS_REGION:us-east-1}
    accesskey: ${AWS_SNS_ACCESS_KEY:teste}
    secretkey: ${AWS_SNS_SECRET_KEY:teste}
    endpointuri: ${AWS_SNS_ENDPOINT:http://localhost:4566}
    resultadoSessaoTopic: ${AWS_SNS_RESULTADO_SESSAO_TOPIC:text-message-topic}