server:
  servlet:
    context-path: /aws

logging:
  level:
    com.aws: ${LOG_LEVEL:DEBUG}

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_SNS_ACCESS_KEY}
        secret-key: ${AWS_SNS_SECRET_KEY}
      sns:
        region: ${AWS_SNS_REGION:us-east-1}
      sqs:
        region: ${AWS_SQS_REGION:us-east-1}
